export const startTimer = 'startTimer'
export const stopTimer = 'stopTimer'
export const askDockerData = 'askDockerData'
export const filterDockerNetworks = 'filterDockerNetworks'
export const selectContainer = 'selectContainer'
