export const startTimer = 'startTimer'
export const stopTimer = 'stopTimer'
export const askDockerData = 'askDockerData'
export const resetDockerFilterForm = 'resetDockerFilterForm'
export const selectContainer = 'selectContainer'
